MVC/Controllers/CitiesController.cs
#nullable disable
using BLL.Controllers.Bases;
using BLL.DAL;
using BLL.Models;
using BLL.Services;
using BLL.Services.Bases;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

// Generated from Custom Template.

namespace MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CitiesController : MvcController
    {
        // Service injections:
        private readonly IService<City, CityModel> _cityService;
        private readonly IService<Country, CountryModel> _countryService;

        /* Can be uncommented and used for many to many relationships. {Entity} may be replaced with the related entiy name in the controller and views. */
        //private readonly IService<{Entity}, {Entity}Model> _{Entity}Service;

        public CitiesController(
            IService<City, CityModel> cityService
            , IService<Country, CountryModel> countryService

            /* Can be uncommented and used for many to many relationships. {Entity} may be replaced with the related entiy name in the controller and views. */
            //, IService<{Entity}, {Entity}Model> {Entity}Service
        )
        {
            _cityService = cityService;
            _countryService = countryService;

            /* Can be uncommented and used for many to many relationships. {Entity} may be replaced with the related entiy name in the controller and views. */
            //_{Entity}Service = {Entity}Service;
        }

        // GET: Cities
        public IActionResult Index()
        {
            // Get collection service logic:
            var list = _cityService.Query().ToList();
            return View(list);
        }

        // GET: Cities/Details/5
        public IActionResult Details(int id)
        {
            // Get item service logic:
            var item = _cityService.Query().SingleOrDefault(q => q.Record.Id == id);
            return View(item);
        }

        protected void SetViewData()
        {
            // Related items service logic to set ViewData (Record.Id and Name parameters may need to be changed in the SelectList constructor according to the model):
            ViewData["CountryId"] = new SelectList(_countryService.Query().ToList(), "Record.Id", "Name");
            
            /* Can be uncommented and used for many to many relationships. {Entity} may be replaced with the related entiy name in the controller and views. */
            //ViewBag.{Entity}Ids = new MultiSelectList(_{Entity}Service.Query().ToList(), "Record.Id", "Name");
        }

        // GET: Cities/Create
        public IActionResult Create()
        {
            SetViewData();
            return View();
        }

        // POST: Cities/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CityModel city)
        {
            if (ModelState.IsValid)
            {
                // Insert item service logic:
                var result = _cityService.Create(city.Record);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Details), new { id = city.Record.Id });
                }
                ModelState.AddModelError("", result.Message);
            }
            SetViewData();
            return View(city);
        }

        // GET: Cities/Edit/5
        public IActionResult Edit(int id)
        {
            // Get item to edit service logic:
            var item = _cityService.Query().SingleOrDefault(q => q.Record.Id == id);
            SetViewData();
            return View(item);
        }

        // POST: Cities/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CityModel city)
        {
            if (ModelState.IsValid)
            {
                // Update item service logic:
                var result = _cityService.Update(city.Record);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Details), new { id = city.Record.Id });
                }
                ModelState.AddModelError("", result.Message);
            }
            SetViewData();
            return View(city);
        }

        // GET: Cities/Delete/5
        public IActionResult Delete(int id)
        {
            // Get item to delete service logic:
            var item = _cityService.Query().SingleOrDefault(q => q.Record.Id == id);
            return View(item);
        }

        // POST: Cities/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            // Delete item service logic:
            var result = _cityService.Delete(id);
            TempData["Message"] = result.Message;
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        // GET: Cities/Get?countryId=1
        public JsonResult Get(int? countryId)
        {
            var cityService = _cityService as CityService;
            var cities = cityService.GetList(countryId);
            return Json(cities.Select(c => new
            {
                value = c.Record.Id,
                text = c.Name
            }));
        }
    }
}

MVC/Controllers/StoresController.cs
#nullable disable
using BLL.Controllers.Bases;
using BLL.DAL;
using BLL.Models;
using BLL.Services;
using BLL.Services.Bases;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

// Generated from Custom Template.

namespace MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class StoresController : MvcController
    {
        // Service injections:
        private readonly IService<Store, StoreModel> _storeService;
        private readonly IService<City, CityModel> _cityService;
        private readonly IService<Country, CountryModel> _countryService;

        /* Can be uncommented and used for many to many relationships. {Entity} may be replaced with the related entiy name in the controller and views. */
        //private readonly IService<{Entity}, {Entity}Model> _{Entity}Service;

        public StoresController(
            IService<Store, StoreModel> storeService
            , IService<City, CityModel> cityService
            , IService<Country, CountryModel> countryService

            /* Can be uncommented and used for many to many relationships. {Entity} may be replaced with the related entiy name in the controller and views. */
            //, IService<{Entity}, {Entity}Model> {Entity}Service
        )
        {
            _storeService = storeService;
            _cityService = cityService;
            _countryService = countryService;

            /* Can be uncommented and used for many to many relationships. {Entity} may be replaced with the related entiy name in the controller and views. */
            //_{Entity}Service = {Entity}Service;
        }

        // GET: Stores
        public IActionResult Index()
        {
            // Get collection service logic:
            var list = _storeService.Query().ToList();
            return View(list);
        }

        // GET: Stores/Details/5
        public IActionResult Details(int id)
        {
            // Get item service logic:
            var item = _storeService.Query().SingleOrDefault(q => q.Record.Id == id);
            return View(item);
        }

        protected void SetViewData(int? countryId = null)
        {
            // Related items service logic to set ViewData (Record.Id and Name parameters may need to be changed in the SelectList constructor according to the model):
            var cityService = _cityService as CityService;
            ViewData["CityId"] = new SelectList(cityService.GetList(countryId), "Record.Id", "Name");
            ViewData["CountryId"] = new SelectList(_countryService.Query().ToList(), "Record.Id", "Name");

            /* Can be uncommented and used for many to many relationships. {Entity} may be replaced with the related entiy name in the controller and views. */
            //ViewBag.{Entity}Ids = new MultiSelectList(_{Entity}Service.Query().ToList(), "Record.Id", "Name");
        }

        // GET: Stores/Create
        public IActionResult Create()
        {
            SetViewData();
            var store = new StoreModel()
            {
                Record = new Store()
                {
                    IsVirtual = true
                }
            };
            return View(store);
        }

        // POST: Stores/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(StoreModel store)
        {
            if (ModelState.IsValid)
            {
                // Insert item service logic:
                var result = _storeService.Create(store.Record);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Details), new { id = store.Record.Id });
                }
                ModelState.AddModelError("", result.Message);
            }
            SetViewData();
            return View(store);
        }

        // GET: Stores/Edit/5
        public IActionResult Edit(int id)
        {
            // Get item to edit service logic:
            var item = _storeService.Query().SingleOrDefault(q => q.Record.Id == id);
            SetViewData(item.Record.CountryId);
            return View(item);
        }

        // POST: Stores/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(StoreModel store)
        {
            if (ModelState.IsValid)
            {
                // Update item service logic:
                var result = _storeService.Update(store.Record);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Details), new { id = store.Record.Id });
                }
                ModelState.AddModelError("", result.Message);
            }
            SetViewData(store.Record.CountryId);
            return View(store);
        }

        // GET: Stores/Delete/5
        public IActionResult Delete(int id)
        {
            // Get item to delete service logic:
            var item = _storeService.Query().SingleOrDefault(q => q.Record.Id == id);
            return View(item);
        }

        // POST: Stores/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            // Delete item service logic:
            var result = _storeService.Delete(id);
            TempData["Message"] = result.Message;
            return RedirectToAction(nameof(Index));
        }
	}
}

MVC/Views/Stores/Create.cshtml
@model StoreModel

@* Generated from Custom Template. *@
@* Model namespace using directive should be added to _ViewImports.cshtml. *@

@{
    var containerDivClass = "container";
    var dateTimePickerClass = "datetimepicker";
}
@{
    ViewData["Title"] = "Store Create";
}

<div class="@containerDivClass">
    <h3>@ViewData["Title"]</h3>
    <hr />
</div>

<div class="@containerDivClass">
    @if (TempData["Message"] is not null)
    {
    <p class="text-danger">
        @TempData["Message"]
    </p>
    }
    <form asp-action="Create" autocomplete="off">
		@Html.AntiForgeryToken()
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row mb-3">
            <label asp-for="Name" class="col-2 col-form-label fw-bold"></label>
			<div class="col-10">
			    <input asp-for="Record.Name" class="form-control" />
				<span asp-validation-for="Record.Name" class="text-danger"></span>
			</div>
        </div>
        <div class="row mb-3">
			<label asp-for="IsVirtual" class="col-2 col-form-label fw-bold"></label>
			<div class="col-10 pt-2">
				<input class="form-check-input" asp-for="Record.IsVirtual" />
            </div>
        </div>
        <div class="row mb-3">
            <label asp-for="Country" class="col-2 col-form-label fw-bold"></label>
            <div class="col-10">
                <select asp-for="Record.CountryId" class="form-select" asp-items="ViewBag.CountryId" onchange="ajaxLoadSelect('#cities', '@Url.Action("Get", "Cities")', { countryId: this.value });">
                    <option value="">-- Select --</option>
                </select>
                <span asp-validation-for="Record.CountryId" class="text-danger"></span>
            </div>
        </div>
        <div class="row mb-3">
            <label asp-for="City" class="col-2 col-form-label fw-bold"></label>
            <div class="col-10">
                <select asp-for="Record.CityId" class="form-select" asp-items="ViewBag.CityId" id="cities">
                    <option value="">-- Select --</option>
                </select>
                <span asp-validation-for="Record.CityId" class="text-danger"></span>
            </div>
        </div>

@* Can be uncommented and used for many to many relationships. {Entity} may be replaced with the related entiy name in the controller and views. *@
        @*
        <div class="row mb-3">
            <label asp-for="{Entity}Ids" class="col-2 col-form-label fw-bold"></label>
	        <div class="col-10">
		        <select multiple asp-for="{Entity}Ids" class="form-select" asp-items="ViewBag.{Entity}Ids"></select>
		        <span asp-validation-for="{Entity}Ids" class="text-danger"></span>
	        </div>
        </div>
        *@

        <hr />  
        <div class="row mb-3">
			<div class="offset-2 col-10">
                <button type="submit" class="btn btn-primary">Save</button>
				&nbsp;&nbsp;
                <button type="reset" class="btn btn-outline-primary">Reset</button>
				&nbsp;&nbsp;
				<a asp-action="Index">Back to List</a>
			</div>
        </div>
    </form>
</div>  

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <partial name="_Ajax" />
}

MVC/Views/Stores/Delete.cshtml
@model StoreModel

@* Generated from Custom Template. *@
@* Model namespace using directive should be added to _ViewImports.cshtml. *@

@{
    var containerDivClass = "container";
}
@{
    ViewData["Title"] = "Store Delete";
}

<div class="@containerDivClass">
    <h3>@ViewData["Title"]</h3>
    <hr />
</div>

@if (Model is not null)
{
<div class="@containerDivClass">
    @if (TempData["Message"] is not null)
    {
    <p class="text-danger">
        @TempData["Message"]
    </p>
    }
    <h3 class="text-danger">Are you sure you want to delete?</h3>
    <hr />
    
    <partial name="_Details" model="Model" />

    <hr />
    <form asp-action="Delete">
	    @Html.AntiForgeryToken()
        <input type="hidden" asp-for="Record.Id" />
        <input type="submit" value="Yes" class="btn btn-danger" />&nbsp;&nbsp;
        <a asp-action="Index" class="btn btn-outline-danger">No</a>
    </form>
</div>
}

MVC/Views/Stores/Details.cshtml
@model StoreModel

@* Generated from Custom Template. *@
@* Model namespace using directive should be added to _ViewImports.cshtml. *@

@{
    var containerDivClass = "container";
}
@{
    ViewData["Title"] = "Store Details";
}

<div class="@containerDivClass">
    <h3>@ViewData["Title"]</h3>
    <hr />
</div>

@if (Model is not null)
{
<div class="@containerDivClass">
    @if (TempData["Message"] is not null)
    {
    <p class="text-danger">
        @TempData["Message"]
    </p>
    }
    
    <partial name="_Details" model="Model" />

    <hr /> 
    <a asp-action="Edit" asp-route-id="@Model.Record.Id">Edit</a>&nbsp;|&nbsp;
    <a asp-action="Delete" asp-route-id="@Model.Record.Id">Delete</a>&nbsp;|&nbsp;
    <a asp-action="Index">Back to List</a>
</div>
}

MVC/Views/Stores/Edit.cshtml
@model StoreModel

@* Generated from Custom Template. *@
@* Model namespace using directive should be added to _ViewImports.cshtml. *@

@{
    var containerDivClass = "container";
    var dateTimePickerClass = "datetimepicker";
}
@{
    ViewData["Title"] = "Store Edit";
}

<div class="@containerDivClass">
    <h3>@ViewData["Title"]</h3>
    <hr />
</div>

@if (Model is not null)
{
<div class="@containerDivClass">
    @if (TempData["Message"] is not null)
    {
    <p class="text-danger">
        @TempData["Message"]
    </p>
    }
    <form asp-action="Edit" autocomplete="off">
	    @Html.AntiForgeryToken()
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Record.Id" />
        <div class="row mb-3">
            <label asp-for="Name" class="col-2 col-form-label fw-bold"></label>
	        <div class="col-10">
	            <input asp-for="Record.Name" class="form-control" />
		        <span asp-validation-for="Record.Name" class="text-danger"></span>
	        </div>
        </div>
        <div class="row mb-3">
		    <label asp-for="IsVirtual" class="col-2 col-form-label fw-bold"></label>
		    <div class="col-10 pt-2">
			    <input class="form-check-input" asp-for="Record.IsVirtual" />
            </div>
        </div>
        <div class="row mb-3">
            <label asp-for="Country" class="col-2 col-form-label fw-bold"></label>
            <div class="col-10">
                <select asp-for="Record.CountryId" class="form-select" asp-items="ViewBag.CountryId" onchange="ajaxLoadSelect('#cities', '@Url.Action("Get", "Cities")', { countryId: this.value });">
                    <option value="">-- Select --</option>
                </select>
                <span asp-validation-for="Record.CountryId" class="text-danger"></span>
            </div>
        </div>
        <div class="row mb-3">
            <label asp-for="City" class="col-2 col-form-label fw-bold"></label>
            <div class="col-10">
                <select asp-for="Record.CityId" class="form-select" asp-items="ViewBag.CityId" id="cities">
                    <option value="">-- Select --</option>
                </select>
                <span asp-validation-for="Record.CityId" class="text-danger"></span>
            </div>
        </div>

@* Can be uncommented and used for many to many relationships. {Entity} may be replaced with the related entiy name in the controller and views. *@
        @*
        <div class="row mb-3">
            <label asp-for="{Entity}Ids" class="col-2 col-form-label fw-bold"></label>
	        <div class="col-10">
		        <select multiple asp-for="{Entity}Ids" class="form-select" asp-items="ViewBag.{Entity}Ids"></select>
		        <span asp-validation-for="{Entity}Ids" class="text-danger"></span>
	        </div>
        </div>
        *@

        <hr />
        <div class="row mb-3">
	        <div class="offset-2 col-10">
                <button type="submit" class="btn btn-primary">Save</button>
		        &nbsp;&nbsp;
                <button type="reset" class="btn btn-outline-primary">Reset</button>
		        &nbsp;&nbsp;
                <a asp-action="Delete" asp-route-id="@Model.Record.Id">Delete</a>
                &nbsp;&nbsp;
		        <a asp-action="Index">Back to List</a>
	        </div>
        </div>
    </form>
</div>
}

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <partial name="_Ajax" />
}

MVC/Views/Stores/Index.cshtml
@model IEnumerable<StoreModel>

@* Generated from Custom Template. *@
@* Model namespace using directive should be added to _ViewImports.cshtml. *@

@{
    var containerDivClass = "container";
}
@{
    ViewData["Title"] = "Store List";
}

<div class="@containerDivClass">
    <h3>@ViewData["Title"]</h3>
    <hr />
</div>

@if (Model is not null)
{
    <form asp-action="Index" autocomplete="off">
        <div class="@containerDivClass">
            <div class="row">
                <div class="col-12 text-danger">
                    @TempData["Message"]
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-10 text-success">
                    @Model.Count() record(s) found.
                </div>
                <div class="col-2 text-end">
                    <a asp-action="Create">Create</a>
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead class="table-secondary">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.IsVirtual)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ProductCount)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.City)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Country)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
		            @foreach (var item in Model) {
				        <tr>
					        <td>
						        @Html.DisplayFor(modelItem => item.Name)
					        </td>
					        <td>
						        @Html.DisplayFor(modelItem => item.IsVirtual)
					        </td>
                            <td>
						        @Html.DisplayFor(modelItem => item.ProductCount)
					        </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.City)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Country)
                            </td>
					        <td class="text-end w-25">
						        <a asp-action="Details" asp-route-id="@item.Record.Id">Details</a>&nbsp;|&nbsp;
						        <a asp-action="Edit" asp-route-id="@item.Record.Id">Edit</a>&nbsp;|&nbsp;
						        <a asp-action="Delete" asp-route-id="@item.Record.Id">Delete</a>
					        </td>
				        </tr>
		            }
                </tbody>
            </table>
        </div>
    </form>
}

MVC/Views/Stores/_Details.cshtml
@model StoreModel

<div class="row mb-3">
    <div class="col-2 fw-bold">
        @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="col-10">
        @Html.DisplayFor(model => model.Name)
    </div>
</div>
<div class="row mb-3">
    <div class="col-2 fw-bold">
        @Html.DisplayNameFor(model => model.IsVirtual)
    </div>
    <div class="col-10">
        @Html.DisplayFor(model => model.IsVirtual)
    </div>
</div>
<div class="row mb-3">
    <div class="col-2 fw-bold">
        @Html.DisplayNameFor(model => model.City)
    </div>
    <div class="col-10">
        @Html.DisplayFor(model => model.City)
    </div>
</div>
<div class="row mb-3">
    <div class="col-2 fw-bold">
        @Html.DisplayNameFor(model => model.Country)
    </div>
    <div class="col-10">
        @Html.DisplayFor(model => model.Country)
    </div>
</div>

@* Can be uncommented and used for many to many relationships. {Entity} may be replaced with the related entiy name in the controller and views. *@
    
<div class="row mb-3">
    <div class="col-2 fw-bold">
        <b>@Html.DisplayNameFor(model => model.Products)</b>
    </div>
    <div class="col-10">
        @Html.Raw(Model.Products)
    </div>
</div>